#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

SConscript("file_management/SCsub")
# SConscript("text_editing/SCsub")
# SConscript("workspaces/SCsub")

env.add_source_files(env.app_sources, "*.cpp")
