#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.app_sources = []

env.add_source_files(env.app_sources, "*.cpp")

SConscript("core/SCsub")
SConscript("drivers/SCsub")
SConscript("file_manager/SCsub")
SConscript("gui/SCsub")
SConscript("icons/SCsub")
SConscript("settings/SCsub")
SConscript("themes/SCsub")

lib = env.add_library("app", env.app_sources)
env.Prepend(LIBS=[lib])
