#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.app_sources = []

env.add_source_files(env.app_sources, "*.cpp")

SConscript("app_core/SCsub")
SConscript("app_modules/SCsub")
SConscript("gui/SCsub")
SConscript("themes/SCsub")

lib = env.add_library("app", env.app_sources)
env.Prepend(LIBS=[lib])
