#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

SConscript("io/SCsub")
SConscript("platform/SCsub")
SConscript("types/SCsub")

env.add_source_files(env.app_sources, "*.cpp")
